function [summary,events] = summarizeDynamicsResults(results,robot)
% SUMMARIZEDYNAMICSRESULTS Time-weighted torque and paired peak states.
t = results.time;
tau = results.torque.total;
qd = results.state.qd;
qdd = results.state.qdd;
power = results.power.joint;
dof = size(tau,2);
[peakAbs,index] = max(abs(tau),[],1);
events = repmat(struct('joint',"",'index',0,'time',0,'q',[], ...
    'qd',[],'qdd',[],'torque',0,'speed',0,'power',0, ...
    'gravity',0,'inertial',0,'velocity',0),dof,1);
for j = 1:dof
    k = index(j);
    events(j).joint = string(robot.structure.jointNames(j));
    events(j).index = k;
    events(j).time = t(k);
    events(j).q = results.state.q(k,:);
    events(j).qd = qd(k,:);
    events(j).qdd = qdd(k,:);
    events(j).torque = tau(k,j);
    events(j).speed = qd(k,j);
    events(j).power = power(k,j);
    events(j).gravity = results.torque.gravity(k,j);
    events(j).inertial = results.torque.inertial(k,j);
    events(j).velocity = results.torque.velocity(k,j);
end
duration = t(end)-t(1);
rmsTorque = sqrt(trapz(t,tau.^2,1)/duration);
maxSpeed = max(abs(qd),[],1);
summary = table(string(robot.structure.jointNames(:)), ...
    max(0,max(tau,[],1)).',min(0,min(tau,[],1)).',peakAbs.',rmsTorque.', ...
    max(0,max(qd,[],1)).',min(0,min(qd,[],1)).',maxSpeed.', ...
    (maxSpeed*60/(2*pi)).',max(abs(qdd),[],1).', ...
    max(0,max(power,[],1)).',min(0,min(power,[],1)).', ...
    max(abs(power),[],1).', ...
    reshape(t(index),[],1),reshape(index,[],1), ...
    reshape(qd(sub2ind(size(qd),index,1:dof)),[],1), ...
    'VariableNames',{'Joint','PeakPositiveTorque_Nm','PeakNegativeTorque_Nm', ...
    'PeakAbsTorque_Nm','RMSTorqueOverTrajectory_Nm', ...
    'MaxPositiveSpeed_rad_s','MaxNegativeSpeed_rad_s', ...
    'MaxAbsSpeed_rad_s','MaxAbsSpeed_rpm', ...
    'MaxAbsAcceleration_rad_s2','PeakPositivePower_W', ...
    'PeakNegativePower_W','PeakAbsPower_W','TimeAtPeakTorque_s', ...
    'SampleAtPeakTorque','SpeedAtPeakTorque_rad_s'});
end
