clear
clc
close all

%% ========================================================================
% PRELIMINARY ROBOT GEOMETRY EXPORT FOR MECHANICAL TEAM
% =========================================================================
%
% Purpose:
%
% Export the current preliminary robot geometry and assumptions into the
% Mechanical handoff folder.
%
% The script exports:
%
%   - Main robot dimensions
%   - Standard DH parameters
%   - Joint limits
%   - Preliminary collision-envelope dimensions
%   - TIG tool / TCP definition
%   - Original WeldingRobot.m configuration file
%   - Complete MATLAB structure
%
% IMPORTANT:
%
% This is PRELIMINARY geometry.
% It must NOT be treated as final CAD dimensions.


%% ========================================================================
% 1. PROJECT PATHS
% =========================================================================

projectRoot = fileparts(fileparts(mfilename("fullpath")));

handoffFolder = fullfile( ...
    projectRoot, ...
    "results", ...
    "mechanicalHandoff");

geometryFolder = fullfile( ...
    handoffFolder, ...
    "geometry");


if ~exist(handoffFolder,"dir")
    mkdir(handoffFolder);
end

if ~exist(geometryFolder,"dir")
    mkdir(geometryFolder);
end


fprintf("\n============================================================\n");
fprintf("PRELIMINARY ROBOT GEOMETRY EXPORT\n");
fprintf("============================================================\n");

fprintf("\nExport folder:\n%s\n\n",geometryFolder);


%% ========================================================================
% 2. CURRENT PRELIMINARY ROBOT GEOMETRY
% =========================================================================
%
% IMPORTANT:
%
% This must match the geometry currently being studied by Simulation.
%
% Current candidate:
%
%       L2 = 425 mm
%       L3 = 375 mm

geometry.d1 = 0.089159;

geometry.L2 = 0.425;
geometry.L3 = 0.375;

geometry.d4 = 0.10915;
geometry.d5 = 0.09465;
geometry.d6 = 0.0823;


%% ========================================================================
% 3. CREATE CANONICAL ROBOT CONFIGURATION
% =========================================================================

robot = config.WeldingRobot(geometry);


%% ========================================================================
% 4. MAIN PHYSICAL GEOMETRY TABLE
% =========================================================================

Parameter = { ...
    'd1'; ...
    'L2'; ...
    'L3'; ...
    'd4'; ...
    'd5'; ...
    'd6'; ...
    'L2 + L3' ...
    };


Value_m = [ ...
    geometry.d1; ...
    geometry.L2; ...
    geometry.L3; ...
    geometry.d4; ...
    geometry.d5; ...
    geometry.d6; ...
    geometry.L2 + geometry.L3 ...
    ];


Value_mm = Value_m * 1000;


Description = { ...
    'Base-to-shoulder vertical DH offset'; ...
    'Main upper-arm link length: shoulder to elbow'; ...
    'Main forearm link length: elbow to wrist'; ...
    'Wrist DH offset d4'; ...
    'Wrist DH offset d5'; ...
    'Final wrist/flange DH offset d6'; ...
    'Total primary arm-link length L2 + L3' ...
    };


Status = { ...
    'Preliminary'; ...
    'Current simulation candidate'; ...
    'Current simulation candidate'; ...
    'Preliminary UR5-scale reference'; ...
    'Preliminary UR5-scale reference'; ...
    'Preliminary UR5-scale reference'; ...
    'Derived' ...
    };


mainGeometryTable = table( ...
    Parameter, ...
    Value_m, ...
    Value_mm, ...
    Description, ...
    Status);


%% ========================================================================
% 5. STANDARD DH PARAMETER TABLE
% =========================================================================
%
% Current UR-style topology:
%
%       a = [0, -L2, -L3, 0, 0, 0]
%       d = [d1, 0, 0, d4, d5, d6]
%
% Standard DH convention.

Joint = (1:6).';


a_m = [ ...
    0; ...
    -geometry.L2; ...
    -geometry.L3; ...
    0; ...
    0; ...
    0 ...
    ];


d_m = [ ...
    geometry.d1; ...
    0; ...
    0; ...
    geometry.d4; ...
    geometry.d5; ...
    geometry.d6 ...
    ];


alpha_rad = [ ...
    pi/2; ...
    0; ...
    0; ...
    pi/2; ...
    -pi/2; ...
    0 ...
    ];


thetaOffset_rad = zeros(6,1);


a_mm = a_m * 1000;

d_mm = d_m * 1000;

alpha_deg = rad2deg(alpha_rad);

thetaOffset_deg = rad2deg(thetaOffset_rad);


dhTable = table( ...
    Joint, ...
    a_m, ...
    a_mm, ...
    d_m, ...
    d_mm, ...
    alpha_rad, ...
    alpha_deg, ...
    thetaOffset_rad, ...
    thetaOffset_deg);


%% ========================================================================
% 6. JOINT LIMIT TABLE
% =========================================================================

jointNames = strings(robot.dof,1);


for i = 1:robot.dof

    if isfield(robot,"joints") && ...
       isfield(robot.joints,"names")

        jointNames(i) = string(robot.joints.names(i));

    else

        jointNames(i) = "J" + string(i);

    end

end


qMin_rad = robot.limits.qMin(:);

qMax_rad = robot.limits.qMax(:);


qMin_deg = rad2deg(qMin_rad);

qMax_deg = rad2deg(qMax_rad);


jointLimitTable = table( ...
    Joint, ...
    jointNames, ...
    qMin_rad, ...
    qMax_rad, ...
    qMin_deg, ...
    qMax_deg);


%% ========================================================================
% 7. PRELIMINARY COLLISION ENVELOPE TABLE
% =========================================================================

collisionParameter = { ...
    'Base radius'; ...
    'Base diameter'; ...
    'Base height'; ...
    'Shoulder radius'; ...
    'Upper-arm envelope radius'; ...
    'Elbow radius'; ...
    'Forearm envelope radius'; ...
    'Wrist 1 radius'; ...
    'Wrist 2 radius'; ...
    'Wrist 3 radius'; ...
    'Flange radius' ...
    };


collisionValue_m = [ ...
    robot.collision.baseRadius; ...
    2*robot.collision.baseRadius; ...
    robot.collision.baseHeight; ...
    robot.collision.shoulderRadius; ...
    robot.collision.upperArmRadius; ...
    robot.collision.elbowRadius; ...
    robot.collision.forearmRadius; ...
    robot.collision.wrist1Radius; ...
    robot.collision.wrist2Radius; ...
    robot.collision.wrist3Radius; ...
    robot.collision.flangeRadius ...
    ];


collisionValue_mm = ...
    collisionValue_m * 1000;


collisionStatus = repmat( ...
    {'Preliminary collision envelope - not final CAD geometry'}, ...
    numel(collisionParameter), ...
    1);


collisionTable = table( ...
    collisionParameter, ...
    collisionValue_m, ...
    collisionValue_mm, ...
    collisionStatus);


%% ========================================================================
% 8. TIG TOOL / TCP TABLE
% =========================================================================

toolParameter = { ...
    'Flange-to-TCP distance'; ...
    'Torch collision-body length'; ...
    'Torch collision-envelope radius' ...
    };


toolValue_m = [ ...
    robot.tool.flangeToTCP; ...
    robot.tool.bodyLength; ...
    robot.tool.bodyRadius ...
    ];


toolValue_mm = ...
    toolValue_m * 1000;


toolDescription = { ...
    'Distance from robot flange frame to welding TCP / tungsten tip'; ...
    'Preliminary physical TIG torch collision-envelope length'; ...
    'Preliminary TIG torch collision-envelope radius' ...
    };


toolTable = table( ...
    toolParameter, ...
    toolValue_m, ...
    toolValue_mm, ...
    toolDescription);


%% ========================================================================
% 9. FLANGE-TO-TCP TRANSFORMATION TABLE
% =========================================================================

T_F_TCP = robot.tool.T_F_TCP;


tcpTransformTable = array2table( ...
    T_F_TCP, ...
    'VariableNames', ...
    {'Column1','Column2','Column3','Column4'}, ...
    'RowNames', ...
    {'Row1','Row2','Row3','Row4'});


%% ========================================================================
% 10. EXPORT EXCEL WORKBOOK
% =========================================================================

excelFile = fullfile( ...
    geometryFolder, ...
    "Preliminary_Robot_Geometry.xlsx");


writetable( ...
    mainGeometryTable, ...
    excelFile, ...
    'Sheet', ...
    'Main Geometry');


writetable( ...
    dhTable, ...
    excelFile, ...
    'Sheet', ...
    'Standard DH');


writetable( ...
    jointLimitTable, ...
    excelFile, ...
    'Sheet', ...
    'Joint Limits');


writetable( ...
    collisionTable, ...
    excelFile, ...
    'Sheet', ...
    'Collision Envelopes');


writetable( ...
    toolTable, ...
    excelFile, ...
    'Sheet', ...
    'TIG Tool');


writetable( ...
    tcpTransformTable, ...
    excelFile, ...
    'Sheet', ...
    'Flange TCP Transform', ...
    'WriteRowNames', ...
    true);


%% ========================================================================
% 11. EXPORT CSV FILES
% =========================================================================

writetable( ...
    mainGeometryTable, ...
    fullfile( ...
        geometryFolder, ...
        "Main_Geometry.csv"));


writetable( ...
    dhTable, ...
    fullfile( ...
        geometryFolder, ...
        "Standard_DH_Parameters.csv"));


writetable( ...
    jointLimitTable, ...
    fullfile( ...
        geometryFolder, ...
        "Joint_Limits.csv"));


writetable( ...
    collisionTable, ...
    fullfile( ...
        geometryFolder, ...
        "Collision_Envelope.csv"));


writetable( ...
    toolTable, ...
    fullfile( ...
        geometryFolder, ...
        "Tool_TCP.csv"));


%% ========================================================================
% 12. SAVE COMPLETE MATLAB CONFIGURATION
% =========================================================================

matFile = fullfile( ...
    geometryFolder, ...
    "Preliminary_Robot_Geometry.mat");


save( ...
    matFile, ...
    "geometry", ...
    "robot", ...
    "mainGeometryTable", ...
    "dhTable", ...
    "jointLimitTable", ...
    "collisionTable", ...
    "toolTable", ...
    "T_F_TCP");


%% ========================================================================
% 13. COPY CANONICAL WeldingRobot.m
% =========================================================================
%
% This gives Mechanical the exact configuration file that generated the
% exported data.

sourceConfigFile = ...
    which("config.WeldingRobot");


if ~isempty(sourceConfigFile)

    copyfile( ...
        sourceConfigFile, ...
        fullfile( ...
            geometryFolder, ...
            "WeldingRobot.m"));

else

    warning( ...
        "Could not locate config.WeldingRobot.m.");

end


%% ========================================================================
% 14. CREATE HUMAN-READABLE README
% =========================================================================

readmeFile = fullfile( ...
    geometryFolder, ...
    "README_PRELIMINARY_GEOMETRY.txt");


fid = fopen( ...
    readmeFile, ...
    "w");


fprintf(fid, ...
    "GRADUATION PROJECT - PRELIMINARY ROBOT GEOMETRY\n");

fprintf(fid, ...
    "================================================\n\n");


fprintf(fid, ...
    "CURRENT MAIN-LINK CANDIDATE\n");

fprintf(fid, ...
    "---------------------------\n");

fprintf(fid, ...
    "L2 = %.1f mm\n", ...
    geometry.L2*1000);

fprintf(fid, ...
    "L3 = %.1f mm\n", ...
    geometry.L3*1000);

fprintf(fid, ...
    "L2 + L3 = %.1f mm\n\n", ...
    (geometry.L2 + geometry.L3)*1000);


fprintf(fid, ...
    "PRELIMINARY FIXED OFFSETS\n");

fprintf(fid, ...
    "-------------------------\n");

fprintf(fid, ...
    "d1 = %.3f mm\n", ...
    geometry.d1*1000);

fprintf(fid, ...
    "d4 = %.3f mm\n", ...
    geometry.d4*1000);

fprintf(fid, ...
    "d5 = %.3f mm\n", ...
    geometry.d5*1000);

fprintf(fid, ...
    "d6 = %.3f mm\n\n", ...
    geometry.d6*1000);


fprintf(fid, ...
    "TIG TOOL\n");

fprintf(fid, ...
    "--------\n");

fprintf(fid, ...
    "Flange-to-TCP = %.1f mm\n", ...
    robot.tool.flangeToTCP*1000);

fprintf(fid, ...
    "Collision body length = %.1f mm\n", ...
    robot.tool.bodyLength*1000);

fprintf(fid, ...
    "Collision envelope radius = %.1f mm\n\n", ...
    robot.tool.bodyRadius*1000);


fprintf(fid, ...
    "IMPORTANT DESIGN STATUS\n");

fprintf(fid, ...
    "-----------------------\n");

fprintf(fid, ...
    "- Robot topology is currently UR5-style 6R.\n");

fprintf(fid, ...
    "- L2 and L3 are the primary geometry variables currently under study.\n");

fprintf(fid, ...
    "- L2 = %.0f mm and L3 = %.0f mm are NOT yet final dimensions.\n", ...
    geometry.L2*1000, ...
    geometry.L3*1000);

fprintf(fid, ...
    "- d1, d4, d5 and d6 currently use preliminary UR5-scale values.\n");

fprintf(fid, ...
    "- Collision radii are simplified Simulation envelopes.\n");

fprintf(fid, ...
    "- They are NOT mechanical housing dimensions.\n");

fprintf(fid, ...
    "- TIG torch geometry is preliminary.\n");

fprintf(fid, ...
    "- Final dimensions require Mechanical packaging and CAD feedback.\n");

fprintf(fid, ...
    "- Final geometry will also be checked using task-level IK,\n");

fprintf(fid, ...
    "  collision, singularity and welding-workspace validation.\n\n");


fprintf(fid, ...
    "MECHANICAL TEAM FEEDBACK REQUESTED\n");

fprintf(fid, ...
    "----------------------------------\n");

fprintf(fid, ...
    "Please provide or constrain:\n");

fprintf(fid, ...
    "1. Feasible L2 and L3 ranges.\n");

fprintf(fid, ...
    "2. Base dimensions.\n");

fprintf(fid, ...
    "3. Shoulder housing dimensions.\n");

fprintf(fid, ...
    "4. Elbow housing dimensions.\n");

fprintf(fid, ...
    "5. Wrist dimensions.\n");

fprintf(fid, ...
    "6. Link cross-sections / thicknesses.\n");

fprintf(fid, ...
    "7. Mechanical joint-angle limits.\n");

fprintf(fid, ...
    "8. Torch-mount geometry.\n");

fprintf(fid, ...
    "9. Cable-routing restrictions affecting joint motion.\n");


fclose(fid);


%% ========================================================================
% 15. PRINT SUMMARY TO MATLAB COMMAND WINDOW
% =========================================================================

fprintf("\n============================================================\n");
fprintf("CURRENT PRELIMINARY GEOMETRY\n");
fprintf("============================================================\n\n");

disp(mainGeometryTable);

fprintf("\nSTANDARD DH PARAMETERS\n");
fprintf("----------------------\n");

disp(dhTable);

fprintf("\nPRELIMINARY COLLISION ENVELOPES\n");
fprintf("--------------------------------\n");

disp(collisionTable);

fprintf("\nTIG TOOL\n");
fprintf("--------\n");

disp(toolTable);


%% ========================================================================
% 16. EXPORT COMPLETE
% =========================================================================

fprintf("\n============================================================\n");
fprintf("GEOMETRY EXPORT COMPLETE\n");
fprintf("============================================================\n");

fprintf("\nFiles saved to:\n%s\n\n",geometryFolder);

fprintf("Generated:\n");
fprintf("  Preliminary_Robot_Geometry.xlsx\n");
fprintf("  Main_Geometry.csv\n");
fprintf("  Standard_DH_Parameters.csv\n");
fprintf("  Joint_Limits.csv\n");
fprintf("  Collision_Envelope.csv\n");
fprintf("  Tool_TCP.csv\n");
fprintf("  Preliminary_Robot_Geometry.mat\n");
fprintf("  WeldingRobot.m\n");
fprintf("  README_PRELIMINARY_GEOMETRY.txt\n\n");