function crossValidateIK()
% validation.crossValidateIK
%
% Simulation Team - IK Cross-Validation
%
% PURPOSE
% Independently validate the Control team's controlIK() against the
% Simulation robot model.
%
% IMPORTANT:
% The target pose is generated by the Simulation rigidBodyTree, NOT by
% controlFK(). The IK solution is then checked again using the Simulation
% rigidBodyTree, NOT by controlFK().
%
% This breaks the circular Control-FK -> Control-IK -> Control-FK test.
%
% Required on MATLAB path:
%   +config/UR5.m
%   controlIK.m
%   controlFK.m
%   controlJacobian.m
%   dhTransform.m
%
% Requires:
%   Robotics System Toolbox

clc;

fprintf('\n');
fprintf('============================================================\n');
fprintf('        SIMULATION TEAM - IK CROSS-VALIDATION\n');
fprintf('============================================================\n\n');

%% 1. Load shared robot configuration

robot = config.UR5();

n = robot.dof;

assert(n == 6, 'Expected a 6-DOF robot.');

a           = robot.kinematics.a(:);
d           = robot.kinematics.d(:);
alpha       = robot.kinematics.alpha(:);
thetaOffset = robot.kinematics.thetaOffset(:);

qMin = robot.limits.qMin(:);
qMax = robot.limits.qMax(:);

assert(numel(a) == n, 'robot.kinematics.a must have DOF entries.');
assert(numel(d) == n, 'robot.kinematics.d must have DOF entries.');
assert(numel(alpha) == n, 'robot.kinematics.alpha must have DOF entries.');
assert(numel(thetaOffset) == n, ...
    'robot.kinematics.thetaOffset must have DOF entries.');
assert(numel(qMin) == n && numel(qMax) == n, ...
    'Joint limits must contain DOF entries.');
assert(isequal(size(robot.tool.T_F_TCP), [4 4]), ...
    'robot.tool.T_F_TCP must be a 4x4 transform.');

fprintf('[1] Shared configuration loaded: PASS\n');

%% 2. Build independent Simulation rigidBodyTree

referenceRobot = rigidBodyTree( ...
    'DataFormat', 'column', ...
    'MaxNumBodies', n + 1);

parentName = referenceRobot.BaseName;

for i = 1:n

    body = rigidBody(sprintf('link%d', i));
    joint = rigidBodyJoint(sprintf('joint%d', i), 'revolute');

    % MATLAB Standard DH order: [a alpha d theta]
    setFixedTransform( ...
        joint, ...
        [a(i), alpha(i), d(i), 0], ...
        'dh');

    body.Joint = joint;
    addBody(referenceRobot, body, parentName);

    parentName = body.Name;
end

% Add fixed flange-to-TCP transform
tcpBody = rigidBody('TCP');
tcpJoint = rigidBodyJoint('TCP_fixed', 'fixed');

setFixedTransform(tcpJoint, robot.tool.T_F_TCP);

tcpBody.Joint = tcpJoint;
addBody(referenceRobot, tcpBody, parentName);

fprintf('[2] Independent rigidBodyTree reference built: PASS\n\n');

%% 3. Use the same five reachable configurations used by Control

qTestsDeg = [
     30   -45    60    20   -30    45
    -30   -60    80   -20    40    60
     60   -30    40    90   -45   -30
    -60   -75    70    30    45   -60
     15   -90    90     0    30    90
];

qTests = deg2rad(qTestsDeg);

numberOfTests = size(qTests,1);

%% 4. IK seed
%
% Use the same zero seed used by the Control team's validation scripts.
% controlIK() itself enforces joint limits internally.

qSeed = zeros(n,1);

%% 5. Independent acceptance tolerances
%
% The Control solver internally uses 1e-6 m and 1e-6 rad.
% We use a slightly looser independent acceptance boundary to avoid
% rejecting a numerically valid solution due only to final floating-point
% evaluation differences.

positionTolerance = 2e-6;      % m
orientationTolerance = 2e-6;   % rad

%% 6. Storage

converged = false(numberOfTests,1);
iterations = zeros(numberOfTests,1);

positionError = inf(numberOfTests,1);
orientationError = inf(numberOfTests,1);

withinLimits = false(numberOfTests,1);
finiteSolution = false(numberOfTests,1);

overallPass = false(numberOfTests,1);

qSolutionStore = nan(n,numberOfTests);
qTargetStore = qTests.';

%% 7. Run IK cross-validation

for k = 1:numberOfTests

    qTarget = qTests(k,:).';

    fprintf('Running IK Test %d...\n', k);

    % =========================================================
    % A) GENERATE TARGET USING SIMULATION MODEL
    % =========================================================
    %
    % This is the crucial independent step.
    % We do NOT call controlFK() here.

    TTargetSimulation = getTransform( ...
        referenceRobot, ...
        qTarget + thetaOffset, ...
        'TCP');

    % =========================================================
    % B) LET CONTROL IK SOLVE THE SIMULATION TARGET
    % =========================================================

    try
        [qSolution, info] = controlIK( ...
            robot, ...
            TTargetSimulation, ...
            qSeed);
    catch ME
        fprintf('  controlIK threw an error:\n');
        fprintf('  %s\n\n', ME.message);
        continue
    end

    qSolution = qSolution(:);

    if numel(qSolution) ~= n
        fprintf('  Returned solution has wrong size.\n\n');
        continue
    end

    qSolutionStore(:,k) = qSolution;

    converged(k) = info.converged;
    iterations(k) = info.iterations;

    finiteSolution(k) = all(isfinite(qSolution));

    if ~finiteSolution(k)
        fprintf('  Returned solution contains NaN/Inf.\n\n');
        continue
    end

    % =========================================================
    % C) VERIFY RETURNED SOLUTION USING SIMULATION MODEL
    % =========================================================
    %
    % Again, we do NOT call controlFK() to judge the result.

    TAchievedSimulation = getTransform( ...
        referenceRobot, ...
        qSolution + thetaOffset, ...
        'TCP');

    % ----- Position error -----

    pTarget = TTargetSimulation(1:3,4);
    pAchieved = TAchievedSimulation(1:3,4);

    positionError(k) = norm(pTarget - pAchieved);

    % ----- TRUE orientation error -----
    %
    % Use the rotation-angle formula rather than relying on the
    % orientation metric stored internally by controlIK().

    RTarget = TTargetSimulation(1:3,1:3);
    RAchieved = TAchievedSimulation(1:3,1:3);

    RRelative = RTarget * RAchieved';

    cosTheta = (trace(RRelative) - 1) / 2;
    cosTheta = max(-1, min(1, cosTheta));

    orientationError(k) = acos(cosTheta);

    % ----- Joint limits -----

    withinLimits(k) = all(qSolution >= qMin - 1e-12) && ...
                      all(qSolution <= qMax + 1e-12);

    % =========================================================
    % D) INDEPENDENT PASS / FAIL
    % =========================================================

    overallPass(k) = ...
        converged(k) && ...
        finiteSolution(k) && ...
        withinLimits(k) && ...
        positionError(k) < positionTolerance && ...
        orientationError(k) < orientationTolerance;

    fprintf('  Converged: %d\n', converged(k));
    fprintf('  Iterations: %d\n', iterations(k));
    fprintf('  Position error: %.3e m\n', positionError(k));
    fprintf('  Orientation error: %.3e rad\n', orientationError(k));
    fprintf('  Within limits: %d\n', withinLimits(k));
    fprintf('  PASS: %d\n\n', overallPass(k));

end

%% 8. Results table

Test = (1:numberOfTests).';

resultsTable = table( ...
    Test, ...
    converged, ...
    iterations, ...
    positionError, ...
    orientationError, ...
    withinLimits, ...
    finiteSolution, ...
    overallPass, ...
    'VariableNames', { ...
        'Test', ...
        'Converged', ...
        'Iterations', ...
        'PositionError_m', ...
        'OrientationError_rad', ...
        'WithinLimits', ...
        'FiniteSolution', ...
        'Pass' ...
    });

fprintf('\nIK CROSS-VALIDATION RESULTS\n');
fprintf('------------------------------------------------------------\n');
disp(resultsTable);

%% 9. Show target and solution configurations
%
% qSolution does NOT need to equal qTarget.
% A 6R robot can have multiple valid IK solutions.

fprintf('\nTARGET vs IK SOLUTION JOINT CONFIGURATIONS [deg]\n');
fprintf('------------------------------------------------------------\n');

for k = 1:numberOfTests

    fprintf('\nTest %d\n', k);

    fprintf('Target-generating q [deg]:\n');
    disp(rad2deg(qTargetStore(:,k)).');

    fprintf('Control IK qSolution [deg]:\n');
    disp(rad2deg(qSolutionStore(:,k)).');

end

%% 10. Overall summary

fprintf('\n============================================================\n');
fprintf(' IK CROSS-VALIDATION SUMMARY\n');
fprintf('============================================================\n');

fprintf('Tests converged: %d / %d\n', ...
    sum(converged), numberOfTests);

fprintf('Solutions within limits: %d / %d\n', ...
    sum(withinLimits), numberOfTests);

fprintf('Independent pose checks passed: %d / %d\n', ...
    sum(positionError < positionTolerance & ...
        orientationError < orientationTolerance), ...
    numberOfTests);

fprintf('Overall tests passed: %d / %d\n', ...
    sum(overallPass), numberOfTests);

fprintf('Worst position error: %.3e m\n', ...
    max(positionError));

fprintf('Worst orientation error: %.3e rad\n', ...
    max(orientationError));

if all(overallPass)

    fprintf('\nOVERALL RESULT: PASS\n');
    fprintf(['Control IK successfully solved all five target poses ', ...
             'generated by the independent Simulation model, and the ', ...
             'returned joint solutions reproduced those poses in the ', ...
             'Simulation model within the acceptance tolerances.\n']);

else

    fprintf('\nOVERALL RESULT: FAIL\n');

    failedTests = find(~overallPass);

    fprintf('Failed test number(s): ');
    fprintf('%d ', failedTests);
    fprintf('\n');

    fprintf(['Inspect convergence, pose error, and joint-limit status ', ...
             'for each failed test before changing the IK algorithm.\n']);

end

fprintf('============================================================\n\n');

end
