function report = validate_dynamics_analysis(robot)
% VALIDATE_DYNAMICS_ANALYSIS Software identities and initial_trial smoke tests.
modelCheck = validateDynamicModel(robot);
if ~modelCheck.pass
    error('validation:InvalidDynamicModel','%s',strjoin(modelCheck.errors,newline));
end
report.model = modelCheck;
originalGravity = robot.model.Gravity;
report.numerical = verifyDynamicsConsistency(robot,struct( ...
    'gravity',[0 0 -9.81],'numSamples',12,'seed',19));
report.oneLink = test_one_link_dynamics();
q0 = robot.params.joints.homePosition;
report.gravity = analyzeGravityLoading(robot,struct( ...
    'gravity',[0 0 -9.81],'q',q0,'numSamples',20,'seed',19));
catalog = robot.gravityPoses;
report.gravityCatalogPresent = ~isempty(catalog) && ...
    any(catalog.names == "home") && ...
    any(catalog.names == "shoulder_horizontal_positive") && ...
    any(catalog.names == "shoulder_horizontal_negative");
report.gravityCatalogIncluded = report.gravity.candidatePoseCount == ...
    size(catalog.q,1) && all(ismember(catalog.names,report.gravity.poseNames));
report.gravityCatalogInLimits = all(all( ...
    catalog.q >= robot.params.joints.positionLimits(:,1).'-1e-12 & ...
    catalog.q <= robot.params.joints.positionLimits(:,2).'+1e-12));
report.gravityCatalogRepeatable = isequal(report.gravity.q, ...
    analyzeGravityLoading(robot,struct('gravity',[0 0 -9.81], ...
    'q',q0,'numSamples',20,'seed',19)).q);
report.gravityCatalogExclusion = analyzeGravityLoading(robot,struct( ...
    'gravity',[0 0 -9.81],'q',q0, ...
    'includeCandidatePoses',false)).candidatePoseCount == 0;
report.gravityOptimized = optimizeGravityLoading(robot,struct( ...
    'gravity',[0 0 -9.81],'numSamples',20,'numStarts',1, ...
    'maxFunctionEvaluations',200,'seed',19));
optimizedPeak = report.gravityOptimized.summaryTable.MaxFoundAbsGravityTorque_Nm;
sampledPeak = report.gravityOptimized.sampled.summaryTable.MaxObservedAbsGravityTorque_Nm;
report.optimizedAtLeastSampled = all(optimizedPeak >= sampledPeak-1e-9);
report.optimizedIncludesCatalog = report.gravityOptimized.sampled.candidatePoseCount ...
    == size(catalog.q,1);
limits = robot.params.joints.positionLimits;
optimizedQ = report.gravityOptimized.qAtMaxAbs;
report.optimizedPosesInLimits = all(all( ...
    optimizedQ >= limits(:,1).'-1e-10 & ...
    optimizedQ <= limits(:,2).'+1e-10));
optimizedModel = copy(robot.model);
optimizedModel.Gravity = [0 0 -9.81];
report.maxOptimizedPoseTorqueError_Nm = 0;
for j = 1:robot.structure.dof
    actual = gravityTorque(optimizedModel,report.gravityOptimized.qAtMaxAbs(j,:));
    report.maxOptimizedPoseTorqueError_Nm = max( ...
        report.maxOptimizedPoseTorqueError_Nm, ...
        abs(actual(j)-report.gravityOptimized.signedTorqueAtMaxAbs_Nm(j)));
end
t = [0; 0.3; 1.1; 2.0];
q = repmat(q0,4,1);
trajectory = struct('time',t,'q',q,'qd',zeros(size(q)),'qdd',zeros(size(q)));
report.staticTrajectory = analyzeTrajectoryDynamics(robot,trajectory, ...
    struct('gravity',[0 0 -9.81]));
expectedStatic = repmat(report.gravity.torque(1,:),4,1);
report.staticTorqueError_Nm = max(abs( ...
    report.staticTrajectory.torque.total(:)-expectedStatic(:)));
report.gravityMoment_Nm = estimateGravityMomentFromCom(robot,q0,[0 0 -9.81]);
report.gravityMomentError_Nm = max(abs(report.gravityMoment_Nm- ...
    report.gravity.torque(1,:)));
report.originalGravity = originalGravity;
report.gravityNotMutated = isequal(robot.model.Gravity,originalGravity);
paramsB = robot.params;
paramsB.geometry.l4 = paramsB.geometry.l4 + 0.03;
robotB = loadRobot(robot.id,paramsB);
qPose = q0;
qPose(2) = deg2rad(40);
tauA = gravityTorqueWithScenario(robot,qPose,[0 0 -9.81]);
tauB = gravityTorqueWithScenario(robotB,qPose,[0 0 -9.81]);
report.geometryTorqueChange_Nm = max(abs(tauB-tauA));
report.geometryPropagates = report.geometryTorqueChange_Nm > 1e-6;
synthetic.time = [0;1;3];
synthetic.state.q = zeros(3,robot.structure.dof);
synthetic.state.qd = zeros(3,robot.structure.dof);
synthetic.state.qdd = zeros(3,robot.structure.dof);
synthetic.torque.total = repmat([0;2;0],1,robot.structure.dof);
synthetic.torque.gravity = zeros(3,robot.structure.dof);
synthetic.torque.inertial = zeros(3,robot.structure.dof);
synthetic.torque.velocity = zeros(3,robot.structure.dof);
synthetic.power.joint = zeros(3,robot.structure.dof);
syntheticSummary = summarizeDynamicsResults(synthetic,robot);
report.nonuniformRmsError_Nm = max(abs( ...
    syntheticSummary.RMSTorqueOverTrajectory_Nm-sqrt(2)));
paramsOverride = robot.params;
paramsOverride.links(3).centerOfMass = [0 0 -0.175];
paramsOverride.links(3).inertia = diag([0.05 0.05 0.01]);
paramsOverride.links(3).dynamics.status = "CAD";
paramsOverride.tool.inertia = diag([0.01 0.02 0.03]);
paramsOverride.tool.dynamics.status = "CAD";
robotOverride = loadRobot(robot.id,paramsOverride);
overrideCheck = validateDynamicModel(robotOverride);
linkCOM = paramsOverride.links(3).centerOfMass(:);
expectedLinkInertia = paramsOverride.links(3).inertia + ...
    paramsOverride.links(3).mass*( ...
    (linkCOM.'*linkCOM)*eye(3)-linkCOM*linkCOM.');
report.explicitInertiaMapping = overrideCheck.pass && ...
    abs(getBody(robotOverride.model,'link_3').Inertia(1)- ...
    expectedLinkInertia(1,1)) < 1e-12 && ...
    ~isequal(robotOverride.model.Bodies{end}.Inertia,robot.model.Bodies{end}.Inertia);
tool = paramsOverride.tool;
segmentLength = norm(tool.TFlangeTCP(1:3,4));
expectedToolIxx = tool.inertia(1,1) + ...
    tool.segmentMass*(3*tool.radius^2+segmentLength^2)/12 + ...
    tool.segmentMass*(segmentLength/2)^2;
report.explicitToolOriginInertiaError_kg_m2 = abs( ...
    robotOverride.model.Bodies{end}.Inertia(1)-expectedToolIxx);
report.pass = report.numerical.pass && report.oneLink.pass && ...
    report.gravityCatalogPresent && report.gravityCatalogIncluded && ...
    report.gravityCatalogInLimits && report.gravityCatalogRepeatable && ...
    report.gravityCatalogExclusion && report.optimizedIncludesCatalog && ...
    report.optimizedAtLeastSampled && ...
    report.optimizedPosesInLimits && ...
    report.maxOptimizedPoseTorqueError_Nm < 1e-8 && ...
    report.staticTorqueError_Nm < 1e-9 && ...
    report.gravityMomentError_Nm < 1e-9 && ...
    report.gravityNotMutated && report.geometryPropagates && ...
    report.nonuniformRmsError_Nm < 1e-12 && ...
    report.explicitInertiaMapping && ...
    report.explicitToolOriginInertiaError_kg_m2 < 1e-12;
fprintf('Dynamics model: %s\n',report.staticTrajectory.meta.label);
fprintf('Max decomposition residual: %.3e N*m\n',report.numerical.maxDecompositionResidual_Nm);
fprintf('Max forward/inverse acceleration error: %.3e rad/s^2\n',report.numerical.maxForwardInverseError_rad_s2);
fprintf('Max mass-matrix asymmetry: %.3e kg*m^2\n',report.numerical.maxMassMatrixAsymmetry_kg_m2);
fprintf('Min mass-matrix eigenvalue: %.3e kg*m^2\n',report.numerical.minMassMatrixEigenvalue_kg_m2);
fprintf('One-link gravity expected/actual: %.6f / %.6f N*m\n', ...
    report.oneLink.expected_Nm,report.oneLink.actual_Nm);
fprintf('One-link inertia expected/actual: %.6f / %.6f kg*m^2\n', ...
    report.oneLink.expectedMassMatrix_kg_m2, ...
    report.oneLink.actualMassMatrix_kg_m2);
fprintf('COM lever-arm gravity check error: %.3e N*m\n',report.gravityMomentError_Nm);
fprintf('Geometry +0.03 m torque change: %.3e N*m\n',report.geometryTorqueChange_Nm);
fprintf('Nonuniform-time RMS check error: %.3e N*m\n',report.nonuniformRmsError_Nm);
fprintf('Explicit COM/inertia mapping valid: %d\n',report.explicitInertiaMapping);
fprintf('Tool origin inertia hand-check error: %.3e kg*m^2\n', ...
    report.explicitToolOriginInertiaError_kg_m2);
fprintf('Per-joint gravity search >= sampled peaks: %d\n',report.optimizedAtLeastSampled);
fprintf('Robot-specific stationary candidate poses included: %d\n', ...
    report.gravity.candidatePoseCount);
fprintf('Optimized pose torque reproduction error: %.3e N*m\n', ...
    report.maxOptimizedPoseTorqueError_Nm);
end

function tau = gravityTorqueWithScenario(robot,q,gravity)
model = copy(robot.model);
model.Gravity = gravity;
tau = gravityTorque(model,q);
end
